### PR TITLE
Closes #70 Wrong env var name

### LINKED ISSUE #70: Correct version() method to point to "VERSION" env variable

### PR DESCRIPTION
**Pull request by jpalvarezl**
Closes #70 
- Pointed to the right env variable

### CODE REVIEW

File: src/config/mod.rs [hunk 1]
```diff
@@ -39,6 +39,6 @@ pub fn build_number() -> Option<String> {
     option_env!("BUILD_NUMBER").map(|it| it.to_string())
 }
 
-pub fn version() -> Option<String> {
-    option_env!("VERSION").map(|it| it.to_string())
+pub fn version() -> String {
+    option_env!("VERSION").unwrap_or(env!("CARGO_PKG_VERSION")).to_string()
```
Comment (rmeissner) [inline src/config/mod.rs:43]: <3
