### PR TITLE
Closes #75: check transfers bug

### LINKED ISSUE #75: [Android] Some of the outgoing tx for ERC20, ERC721, ETH are displayed as custom tx
@liliya-soroka commented on [Thu Aug 06 2020](https://github.com/gnosis/safe-android/issues/782)

**Describe the bug**
Custom transactions are displayed for some of the ERC20, ERC721, ETH outgoing tx
Actual for the transactions in waiting for confirmation and executed statuses

**To Reproduce**
-----------
ERC20 and ERC721:
1. Go to the safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Open transactions details
3. Check txs with nonce 176,175,174 
-----------
ETH:
1. Go to the safe 0x938bae50a210b80EA233112800Cd5Bc2e7644300
2. Open transactions details
3. Check txs with 46

**Expected behavior**
If it's outgoing ERC20 or ERC721 tx it should be displayed as outgoing tx ( not custom)

**Screenshots**
in android app 

on web 

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 1.12.1-79

**Additional context**

### PR DESCRIPTION
**Pull request by rmeissner**
Closes #75: check transfers bug

- Add tests for cases reported
- Fix parsing of value string
- Don't check sender and receipient for transfer calls

### CODE REVIEW

**Comment by rmeissner** [comment]
This is a quick fix ... we should probably refactor this a little once we have 1.0.0 ... it is not super bad, but we could probably make this nicer (there is also the todo to use enums)

File: src/models/converters/transactions/mod.rs [hunk 1]
```diff
@@ -2,6 +2,8 @@ extern crate chrono;
 
 pub mod details;
 pub mod summary;
+
+#[cfg(test)]
```
Comment (jpalvarezl) [inline src/models/converters/transactions/mod.rs:6]: I am not sure this is how it works. This should probably be wherever you have the methods annotated with `#[test]`

File: src/models/converters/transactions/tests/summary.rs [hunk 2]
```diff
@@ -1,419 +1,205 @@
...
-            signatures: Some(String::from("0x00000000000000000000000065f8236309e5a99ff0d129d04e486ebce20dc7b0000000000000000000000000000000000000000000000000000000000000000001ccbf629ad44c41c39e397d4c3c199593be908edf57d728204c2ebd5f384ad5c90f1e7fca86dab291e406724b99d7d956acaa01cb78d146e410a7accd1ffe0df01b9b3733a7018e90ca4ebb1504e1c230260f8d41d0542180e915fa10af694f18b360f5fe6c9dc252e257b3d45071b32977224122165ff771a018a392bb62dbf1491b")),
-        };
-        let token_info = Some(TokenInfo {
-            token_type: TokenType::Erc20,
-            address: String::from("0xF9bA5210F91D0474bd1e1DcDAeC4C58E359AaD85"),
-            name: String::from("Maker"),
-            symbol: String::from("MKR"),
-            decimals: 18,
-            logo_uri: Some(String::from("https://gnosis-safe-token-logos.s3.amazonaws.com/0xF9bA5210F91D0474bd1e1DcDAeC4C58E359AaD85.png")),
+use crate::models::converters::transactions::{data_size};
```
Comment (jpalvarezl) [inline src/models/converters/transactions/tests/summary.rs:1]: I think this is where you need to have `#[cfg(test)]` . Could be the reason Travis is complaining.

File: src/models/converters/transactions/tests/summary.rs [hunk 3]
```diff
@@ -1,419 +1,205 @@
...
+    assert!(error.is_err());
+}
+
+#[test]
+fn module_tx_to_summary_transaction() {
+    let expected_to = String::from("0x12345789");
+    let expected_date = Utc::now();
+    let expected_date_in_millis = expected_date.timestamp_millis();
+    let module_tx = ModuleTransaction {
+        created: String::from("created"),
```
Comment (jpalvarezl) [inline src/models/converters/transactions/tests/summary.rs:38]: This makes me think that we should probably define `created` as `DateTime<Utc>`. Some typing would be nice.

File: src/models/converters/transactions/tests/summary.rs [hunk 4]
```diff
@@ -1,419 +1,205 @@
...
-                    transaction_hash: None, 
-                    signature_type: String::from("EOA"),
-                    signature: Some(String::from("0x75aa624315ed8a72e1fcf396fe8d7a50d6d71f18c3b6bddb025bf426b7e4de3f52ead25cef15c9b35feaeefb2b81f2b5333ed949035f948fbe0a9aec56f7ac5b1b")),
-                },
-                Confirmation {
-                    owner: String::from("0xF2CeA96575d6b10f51d9aF3b10e3e4E5738aa6bd"),
-                    submission_date: Some(expected_date),
-                    transaction_hash: None, 
-                    signature_type: String::from("EOA"),
-                    signature: Some(String::from("0x000000000000000000000000f2cea96575d6b10f51d9af3b10e3e4e5738aa6bd000000000000000000000000000000000000000000000000000000000000000001")),
```
Comment (jpalvarezl) [inline src/models/converters/transactions/tests/summary.rs]: What happened to these tests?

Comment (rmeissner) [reply src/models/converters/transactions/tests/summary.rs]: I forgot to add the new files :facepalm:

File: src/models/converters/transactions/tests/summary.rs (hunk 3 above)
Comment (rmeissner) [reply src/models/converters/transactions/tests/summary.rs:38]: These tests/ models are unrelated to this PR, but we could create an issue to remove this field, as we don't require it.

File: src/models/converters/transactions/tests/summary.rs (hunk 2 above)
Comment (rmeissner) [reply src/models/converters/transactions/tests/summary.rs:1]: nope, I was just missing 2 files that's why it is complaining ;)

File: src/models/converters/transactions/mod.rs (hunk 1 above)
Comment (rmeissner) [reply src/models/converters/transactions/mod.rs:6]: this works ... I tested it quite thoroughly ;)

File: src/models/converters/transactions/tests/transfer_type_checks.rs [hunk 5]
```diff
@@ -0,0 +1,213 @@
...
+                submission_date: Some(expected_date),
+                transaction_hash: None, 
+                signature_type: String::from("EOA"),
+                signature: Some(String::from("0x75aa624315ed8a72e1fcf396fe8d7a50d6d71f18c3b6bddb025bf426b7e4de3f52ead25cef15c9b35feaeefb2b81f2b5333ed949035f948fbe0a9aec56f7ac5b1b")),
+            },
+            Confirmation {
+                owner: String::from("0xF2CeA96575d6b10f51d9aF3b10e3e4E5738aa6bd"),
+                submission_date: Some(expected_date),
+                transaction_hash: None, 
+                signature_type: String::from("EOA"),
```
Comment (jpalvarezl) [inline src/models/converters/transactions/tests/transfer_type_checks.rs:65]: I was wondering if we should pass this on to the clients. I think Uxio told us we could ignore it, but not sure if sometime down the road this will become relevant.

Comment (rmeissner) [reply src/models/converters/transactions/tests/transfer_type_checks.rs:65]: the confirmation_type can be ignored, not the signature_type

Comment (rmeissner) [reply src/models/converters/transactions/tests/transfer_type_checks.rs:65]: Also it is currently not passed along, right? This is something that needs to be evaluated after 1.0.0 (as it might be required for the web app)
