### PR TITLE
Fix config_uri macro uri formatting

### LINKED ISSUE #489: Fix ` config_uri` macro
Currently the `config_uri` macro is building the uri using `<base>/<path>` as `path` is commonly provided with a leading `/` the path  has `//` which is unexpected.

Note: we should also add tests for this

### PR DESCRIPTION
**Pull request by fmrsabino**
Closes #489 

- Remove the extra `/` in the `config_uri` macro – the paths already include the initial slash.

### CODE REVIEW

File: src/macros.rs [hunk 1]
```diff
@@ -86,10 +87,30 @@ macro_rules! core_uri {
...
-        format!("{}/{}", $crate::config::base_config_service_url(), $path)
+        format!("{}{}", $crate::config::base_config_service_url(), $path)
     }};
     ($path:literal, $($arg:tt)*) => {{
         let full_path: String = format!($path, $($arg)*);
         config_uri!(full_path)
     }};
 }
+
+#[test]
```
Comment (rmeissner) [inline src/macros.rs:98]: We normally put our tests in separate test files

File: src/macros.rs [hunk 2]
```diff
@@ -1,3 +1,4 @@
+use std::env;
```
Comment (rmeissner) [inline src/macros.rs:1]: This is only required for the test, right?

File: src/macros.rs (hunk 1 above)
Comment (fmrsabino) [reply src/macros.rs:98]: Ah yes. I was discussing with @jpalvarezl regarding this because the `macros` live in the root `src` dir. I thought about moving to a different folder 🤔 What's your recommendation here?

File: src/macros.rs (hunk 2 above)
Comment (fmrsabino) [reply src/macros.rs:1]: Correct. I should scope this import.

File: src/macros.rs (hunk 1 above)
Comment (rmeissner) [reply src/macros.rs]: No strong opinion, but it should be consistent in our project

Comment (jpalvarezl) [reply src/macros.rs]: We could move them to `/utils/tests/macros.rs`

Comment (fmrsabino) [reply src/macros.rs]: Yes I can do that. For me it was just that the macros are on `/src/macros.rs/` and not under `src/utils`

Comment (fmrsabino) [reply src/macros.rs]: Moved in 2b21092

**Review by jpalvarezl — APPROVED** [review]
