### PR TITLE
Error forwading for notification endpoints

### LINKED ISSUE #476: Implement error forwarding for notification endpoints
Un-registering:
 - No errors, nothing but a 200
 - forwards the error fully

Registering:
 - No errors, nothing but a 200
 - Partial errors, provide a (service side?) return list of failed ids. 
 - Error on the request to the gw, errors as usual

### PR DESCRIPTION
**Pull request by jpalvarezl**
Closes #476 

Current state:

The CGW responds with a status code `500` and the following body:

```json
{
    "code": 1337,
    "message": "Push notification registration failed for chain ids: 1, 4"
}
```
Where the `chain_id`s that failed are listed at the end of the `message` field

### CODE REVIEW

File: src/macros.rs [hunk 1]
```diff
@@ -27,10 +27,10 @@ macro_rules! create_id {
 
 macro_rules! bail {
     ($msg:literal $(,)?) => {
-        return Err($crate::api_error!($msg))
```
Comment (fmrsabino) [inline src/macros.rs:30]: For the Rust newbie: what does this accomplish? 😄

**Review by fmrsabino — APPROVED** [review]

File: src/macros.rs (hunk 1 above)
Comment (jpalvarezl) [reply src/macros.rs:30]: just because we have `return` somehow in the past it was working though not sure why :/

File: src/services/notifications.rs [hunk 2]
```diff
@@ -41,35 +40,68 @@ pub async fn post_registration(
...
+            };
+        }
+        output
+    };
 
-    Ok(())
+    if chain_id_errors.is_empty() {
+        Ok(())
+    } else {
+        bail!(
```
Comment (rmeissner) [inline src/services/notifications.rs:79]: Could we document the expected response in the PR description and let the client teams give a :+1: ?

File: src/services/notifications.rs [hunk 3]
```diff
@@ -41,35 +40,68 @@ pub async fn post_registration(
...
+            } else {
+                // reqwest failures (unreachable urls, do we need to handle?)
+                output.push(chain_id);
+            };
+        }
+        output
+    };
 
-    Ok(())
+    if chain_id_errors.is_empty() {
```
Comment (rmeissner) [inline src/services/notifications.rs:76]: For this logic a `boolean` would be enough, no need to create a vector

File: src/services/notifications.rs [hunk 4]
```diff
@@ -41,35 +40,68 @@ pub async fn post_registration(
...
         notification_device_data: device_data.clone(),
-        safes: safe_registration.safes,
-        signatures: safe_registration.signatures,
+        safes: safe_registration.safes.to_owned(),
+        signatures: safe_registration.signatures.to_owned(),
+    }
+}
+
+async fn forward_error(response: reqwest::Response) -> ApiResult<()> {
+    if !response.status().is_success() {
```
Comment (rmeissner) [inline src/services/notifications.rs:98]: Would it be nicer to switch this if around to avoid the "not"?

File: src/services/notifications.rs (hunk 3 above)
Comment (jpalvarezl) [reply src/services/notifications.rs:76]: We basically use the vector anyway afterwards, as it contains the `chain_id`s of the failed requests that the clients wanted to keep track of.

**Review by rmeissner — APPROVED** [review]
